### ISSUE TITLE
Emoji no retorno da requisição

### ISSUE THREAD

**Issue by jonathantorioni** [chipytux/correiosApi#1]
Percebi que ao realizar a requisição  para o endereço:
https://api.linketrack.com/track/json?user=teste&token=1abcd00b2731640e886fb41a8a9671ad1434c599dbaa0a0de9a5aa619f29a83f&codigo=PZ318065739BR
O JSON retorna os icones de emoji em substatus, dessa forma a integração do meu sistema não consegue realizar a interpretação desses emoji.

Antes o substatus armazenava a origem e o destino do objeto para determinado evento.

**Comment by chipytux** [comment]
Boa tarde @JonathanTorioni, 

Você poderia me informar qual me informar qual era o código "host" da requisição, para que possamos reproduzir o erro?

**Comment by jonathantorioni** [comment]
Neste exato momento está acontecendo o problema dos emojis... Hoje no periodo da tarde não tinha mais acontecido o erro.
https://ik.imagekit.io/xdo41a0f2n/Screenshot_1_Onxpr1Xcu.png

Ele de ficava assim antes:
https://ik.imagekit.io/xdo41a0f2n/Screenshot_2_zavioZZMy.png

**Comment by chipytux** [comment]
Olá, @JonathanTorioni.

Obrigado pelo Feedback. 
Já encontramos a origem dos Emojis 😀, e já removemos.
