### ISSUE TITLE
Falha na informação de encaminhamento

### ISSUE THREAD

**Issue by shadowslords** [chipytux/correiosApi#2]
Chipytux, primeiramente parabéns pela API, comecei a usar agora e já estou gostando muito.

Porem logo nos primeiros usos percebi que quando recebia a notificação de que uma encomenda foi encaminhada de uma unidade de distribuição para outra o local de destino não estava aparecendo, verifiquei a saída no browser e percebi que também não aparece o destino.
Conforme esse exemplo (observe que no "Para: Unidade de Distribuição"]}" não aparece o destino): 

{"codigo":"NX000000000BR","host":"av","eventos":[{"status":"Objeto entregue ao destinatário","local":"Unidade de Distribuição/VITORIA/ES","data":"17/11/2021","hora":"14:36","subStatus":[]},{"status":"Objeto saiu para entrega ao destinatário","local":"Unidade de Distribuição/VITORIA/ES","data":"17/11/2021","hora":"11:53","subStatus":[]},{"status":"Objeto encaminhado","local":"Unidade de Tratamento/SERRA/ES","data":"13/11/2021","hora":"09:59","subStatus":["De: Unidade de Tratamento/SERRA/ES Para: Unidade de Distribuição"]},{"status":"Objeto encaminhado","local":"Unidade de Logística Integrada/CURITIBA/PR","data":"09/11/2021","hora":"11:53","subStatus":["De: Unidade de Logística Integrada/CURITIBA/PR Para: Unidade de Tratamento"]},{"status":"Fiscalização aduaneira finalizada","local":"Unidade Operacional/CURITIBA/PR","data":"09/11/2021","hora":"11:10","subStatus":[]},{"status":"Objeto recebido pelos Correios do Brasil","local":"Unidade de Logística Integrada/CURITIBA/PR","data":"08/11/2021","hora":"17:24","subStatus":["<span class=\"minhasImportacoes\">Acesse o ambiente <a href=\"https://www.correios.com.br/encomendas-logistica/minhas-importacoes/minhas-importacoes\" target=\"_blank\">Minhas Importações</a></span>"]},{"status":"Objeto postado","local":"País//","data":"02/11/2021","hora":"06:50","subStatus":[]}],"time":0.618,"quantidade":7,"servico":"EDEI ENCOMENDA NAO URGENTE","ultimo":"2021-11-17T17:36:00.000Z"}

**Comment by chipytux** [comment]
> :warning: O valor do campo `subStatus` varia de acordo com a fonte do rastreamento e não deve ser considerado: **Este campo será descontinuado no futuro!!**

Obrigado pelo feedback.
