### ISSUE TITLE
Códigos não localizados

### ISSUE THREAD

**Issue by otomay** [chipytux/correiosApi#3]
Olá, amigo!

Uso a API tem alguns anos (muito obrigado pelo trabalho, inclusive) e recentemente comecei me deparar com alguns códigos que não retornam resultados pela linketrack, enquanto que no front dos correios retorna.

Exemplo:

`{"codigo":"TF339232785BR","host":"rd","eventos":[],"time":0.033,"quantidade":0,"servico":""}`

![image](https://github.com/chipytux/correiosApi/assets/54224340/86afc5bb-688b-4bef-b479-33b5dfd49338)

No front do linketrack também não funciona:

![image](https://github.com/chipytux/correiosApi/assets/54224340/52adaf8a-4493-443d-a67e-6b48762cf061)

**Comment by chipytux** [comment]
Obrigado pelo feedback @otomay. O problema jã tinha sido resolvido na mesma data, mas acabei esquecendo de fechar a issue.
